fastlane_version "2.5.0"

default_platform :ios

platform :ios do

    xcode_select "/Applications/Xcode.app"
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
    lane :exp do |values|
        # Fabric generated this lane for deployment to Crashlytics Beta
        # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
        # match
        sigh(username: 'c@harl.ie', app_identifier: 'com.charliewilliams.ExperimentalTask', adhoc: true)
        gym(scheme: values[:scheme] ? values[:scheme] : 'ExperimentalTask', export_method: 'ad-hoc', export_xcargs: "-allowProvisioningUpdates")
        increment_build_number

        emails = values[:test_email] ? values[:test_email] : ['c@charliewilliams.org', 'ahalpern@bucknell.edu', 'Karen.Wise@gsmd.ac.uk', 'sms063@bucknell.edu', 'beth.martin@gsmd.ac.uk', 'bethsuzannemarti@aol.com', 'bethsuzannemartin@hotmail.com', 'elaine_burrows@hotmail.com', 'abigail.f.skinner@gmail.com', 'danby318@gmail.com', 'inglis291@hotmail.com', 'julian@firstcallmedia.co.uk', 'hayden@davies07.com', 'Angela.Jones@jrs.ac.uk', 'pdance90@gmail.com', 'angela.mistyblue@outlook.com', 'angela.mistyblue@gmail.com']

        notes = changelog_from_git_commits ? changelog_from_git_commits : ""

        groups = nil

        crashlytics(api_token: '3bf576a7e0e1a634037b4c20ef79f63196a6eb0f',
        build_secret: 'cdb8002da5b7da3cfd6f90faa82a27e0d488250d853761f7c834a9200ca71c52',
        emails: emails,
        groups: groups,
        notes: notes,
        notifications: false) # Should this distribution notify your testers via email?

        # for all available options run `fastlane action crashlytics`

        # You can notify your team in chat that a beta build has been uploaded
        slack(
        slack_url: "https://hooks.slack.com/services/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",
        channel: "general",
        message: "New beta version at https://fabric.io/_/beta \n\n" + notes
        )
    end

  lane :control do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    # match
    sigh(username: 'c@harl.ie', app_identifier: 'com.charliewilliams.ControlTask', adhoc: true)
    gym(scheme: values[:scheme] ? values[:scheme] : 'ControlTask', export_method: 'ad-hoc', export_xcargs: "-allowProvisioningUpdates")
	  increment_build_number

    emails = values[:test_email] ? values[:test_email] : ['c@charliewilliams.org', 'ahalpern@bucknell.edu', 'Karen.Wise@gsmd.ac.uk', 'sms063@bucknell.edu', 'beth.martin@gsmd.ac.uk', 'bethsuzannemarti@aol.com', 'bethsuzannemartin@hotmail.com', 'elaine_burrows@hotmail.com', 'abigail.f.skinner@gmail.com', 'danby318@gmail.com', 'inglis291@hotmail.com', 'julian@firstcallmedia.co.uk', 'hayden@davies07.com', 'Angela.Jones@jrs.ac.uk', 'pdance90@gmail.com', 'angela.mistyblue@outlook.com', 'angela.mistyblue@gmail.com']

    notes = changelog_from_git_commits ? changelog_from_git_commits : ""

    groups = nil

    crashlytics(api_token: '3bf576a7e0e1a634037b4c20ef79f63196a6eb0f',
             build_secret: 'cdb8002da5b7da3cfd6f90faa82a27e0d488250d853761f7c834a9200ca71c52',
                   emails: emails,
                   groups: groups,
                    notes: notes,
            notifications: false) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    slack(
       slack_url: "https://hooks.slack.com/services/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",
       channel: "general",
       message: "New beta version at https://fabric.io/_/beta \n\n" + notes
     )
  end
end
